# styles.py
"""
Paleta de cores e estilos para barras de status.
"""

# Cores ANSI
COLOR_RED = "\033[91m"
COLOR_PURPLE = "\033[95m"
COLOR_BLUE1 = "\033[34m"
COLOR_BLUE2 = "\033[36m"
COLOR_BLUE3 = "\033[96m"
COLOR_GREEN1 = "\033[92m"
COLOR_GREEN2 = "\033[32m"
COLOR_BROWN = "\033[33m"
COLOR_YELLOW = "\033[93m"
COLOR_GREY = "\033[37m"
COLOR_DEFAULT = "\033[0m"
COLOR_DARK = "\033[90m"

COLOR_LIST = [
    COLOR_RED, COLOR_PURPLE, COLOR_BLUE1, COLOR_BLUE2, COLOR_BLUE3,
    COLOR_GREEN1, COLOR_GREEN2, COLOR_YELLOW, COLOR_BROWN, COLOR_GREY, COLOR_DEFAULT, COLOR_DARK
]

SYMBOL_BLOCK = "█"
SYMBOL_EMPTY = "_"

# Box Drawing Characters
BOX_TL = "╔"
BOX_TR = "╗"
BOX_BL = "╚"
BOX_BR = "╝"
BOX_H = "═"
BOX_V = "║"
BOX_T = "╤"
BOX_B = "╧"
